gui:
  theme:
    activeBorderColor:
      - '#cba6f7'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#cba6f7'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'
      - bold

git:
  autoFetch: false
  paging:
    colorarg: always
    # pager: delta --dark --paging=never
    externalDiffCommand: difft --color=always

reporting: "off"
disableStartupPopups: true

keybinding:
  universal:
    prevBlock: '<c-k>' # goto the previous block / panel
    nextBlock: '<c-j>' # goto the next block / panel
  commits:
    moveDownCommit: '<left>' # move commit down one
    moveUpCommit: '<right>' # move commit up one
