---
- hosts: localhost
  become: yes
  tasks:
    - name: Swap keyboard layout
      replace:
        path: /etc/default/keyboard
        regexp: 'us'
        replace: 'fr'
    - name: Install core
      apt:
        name:
          - dkms 
          - build-essential 
          - cmake 
          - cmake-data 
          - openssh-server 
          - alsa-utils
          - autoconf
          - procps
          - file
          - isenkram-cli
          - network-manager
    - name: Add monzey to sudoers
      shell: echo "monzey  ALL=(ALL) NOPASSWD:ALL" | tee /etc/sudoers.d/monzey
    - name: Add missing firmwares
      shell: isenkram-autoinstall-firmware
    - name: Install go
      block: 
        - name: Unarchive go
          unarchive: 
            src: https://golang.org/dl/go1.17.linux-amd64.tar.gz
            dest: /usr/local
            remote_src: yes
        - name: Source go
          shell: export PATH=/usr/local/go/bin:${PATH}
    - name: Install dev utils
      apt:
        name:
          - stow 
          - zsh 
          - ranger 
          - silversearcher-ag 
          - openvpn
          - bat
          - fzf
          - exa
          - unzip
          - zip
        update_cache: yes
    - name: Install secondary deps
      apt:
        name: 
          - i3
          - dmenu
          - openresolv
          - rsync
          - uthash-dev 
          - meson
          - pkg-config
          - xcb-proto 
          - xcb 
          - imagemagick
          - sudo
          - chromium 
          - firefox-esr
          - xfonts-base 
          - xserver-xorg-input-all 
          - xinit 
          - xserver-xorg 
          - xserver-xorg-video-all 
          - cargo 
          - tig 
          - feh 
          - compton 
          - suckless-tools 
          - xclip 
          - bison 
          - flex
          - dbus-x11 
          - dirmngr 
          - ffmpeg 
          - x11-apps 
          - mpc
          - polybar
          - nscd
          - mpv
        update_cache: yes
    - name: Install antigen
      get_url:
        url: https://git.io/antigen
        dest: /usr/local/bin/antigen
    - name: Install nvim
      get_url:
        url: https://github.com/neovim/neovim/releases/download/v0.10.0/nvim.appimage
        dest: /usr/bin/nvim
        mode: '0655'
    - name: Add ssh directory
      file:
        path: ~/.ssh
        state: directory
        mode: '0755'
      become_user: monzey
    - name: Add ssh key
      community.crypto.openssh_keypair:
        path: ~/.ssh/id_rsa
        size: 4096
        type: rsa
        comment: maxi.bertrand@gmail.com
      become_user: monzey
    - name: Install chrome
      shell: |
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -O chrome.deb
        dpkg -i chrome.deb
      args:
        chdir: /tmp
    - name: Clone dunst
      git:
        repo: https://github.com/dunst-project/dunst.git
        dest: /tmp/dunst
    - name: Install dunst
      shell: |
        make
        make install
      args:
        chdir: /tmp/dunst
    - name: Remove current rustc
      apt:
        name: rustc
        state: absent
    - name: Install rust
      block: 
      - name: Download rust
        shell: | 
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        args:
      - name: Copy rust to path
        copy: 
          src: /$HOME/.cargo/bin/rustc
          dest: /usr/bin/rustc
          mode: '0755'
    - name: Link cargo
      copy: 
        src: /$HOME/.cargo/bin/cargo
        dest: /usr/bin/cargo
        mode: '0755'
    - name: Install delta
      block:
        - name: Install delta globally
          shell: cargo install git-delta
        - name: Install delta for user
          copy: 
            src: /$HOME/.cargo/bin/delta
            dest: /usr/bin/delta
            mode: '0755'
    - name: Install neovide
      block:
        - name: Download neovide
          get_url: 
            url: https://github.com/neovide/neovide/releases/download/0.13.3/neovide-linux-x86_64.tar.gz
            dest: /tmp/neovide.tar.gz
        - name: Unarchive neovide
          shell: mkdir neovide && tar -zxvf neovide.tar.gz -C neovide
          args:
            chdir: /tmp
        - name: Install neovide
          copy: 
            src: /tmp/neovide/neovide
            dest: /usr/bin/neovide
            mode: '0755'
    - name: Install lazygit
      block:
        - name: Download lazygit
          get_url: 
            url: https://github.com/jesseduffield/lazygit/releases/download/v0.44.0/lazygit_0.44.0_Linux_x86_64.tar.gz
            dest: /tmp/lazygit.tar.gz
        - name: Unarchive lazygit
          shell: mkdir lazygit && tar -zxvf lazygit.tar.gz -C lazygit
          args:
            chdir: /tmp
        - name: Install lazygit
          copy: 
            src: /tmp/lazygit/lazygit
            dest: /usr/bin/lazygit
            mode: '0755'
    - name: Install btop
      block:
        - name: Download btop
          get_url: 
            url: https://github.com/aristocratos/btop/releases/download/v1.2.5/btop-x86_64-linux-musl.tbz 
            dest: /tmp/btop.tbz
        - name: Unarchive btop
          shell: mkdir btop && tar -xjf btop.tbz -C btop
          args:
            chdir: /tmp
        - name: Install btop exe
          shell: make install
          args:
            chdir: /tmp/btop
    - name: Install kitty
      block:
      - name: Download kitty
        shell: curl -l https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin dest=/usr/bin launch=n
      - name: Change kitty ownership
        file: 
          src: /usr/bin/kitty.app/bin/kitty
          dest: /usr/bin/kitty
          mode: '0755'
          state: link
    - name: Install ripgrep
      apt:
        deb: https://github.com/BurntSushi/ripgrep/releases/download/14.1.0/ripgrep_14.1.0-1_amd64.deb
    - name: Install slack
      apt:
        deb: https://downloads.slack-edge.com/releases/linux/4.23.0/prod/x64/slack-desktop-4.23.0-amd64.deb
    - name: Recdsk
      copy:
        src: recdsk
        dest: /usr/bin/recdsk
        mode: a+x
    - name: Install fonts
      copy:
        src: "{{ item }}"
        dest: /usr/share/fonts
      with_fileglob:
        - fonts/*
    - name: Update fonts cache
      shell: fc-cache -fv
    - name: Install cursor theme
      copy:
        src: "{{ item }}"
        dest: /usr/share/icons/default
      with_fileglob:
        - cursor/*
    - name: Install VPN
      block:
        - name: Copy script to init.d
          file:
            src: "{{ playbook_dir }}/init.d/openvpncustom"
            dest: /etc/init.d/openvpncustom
            state: link
        - name: Add script to startup
          shell: update-rc.d openvpncustom defaults
    - name: Install nvm
      shell: |
        wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
      become_user: monzey
    - name: Install node 
      shell: |
        source $HOME/.nvm/nvm.sh
        nvm install {{ item }}
        nvm use {{ item }}
      args:
        executable: /bin/bash
      loop:
        - 16.13.0
      become_user: monzey
    - name: Clone dotfiles
      git:
        repo: https://github.com/monzey/dotfiles.git
        dest: $HOME/dotfiles
      become_user: monzey
    - name: Wrap up user install
      script: install.sh
      args:
        chdir: /home/monzey/dotfiles
      become_user: monzey
