---
- hosts: localhost
  become: yes
  # vars:
  tasks:
    - name: Swap keyboard layout
      replace:
        path: /etc/default/keyboard
        regexp: 'us'
        replace: 'fr'
    - name: Install core
      apt:
        name:
          - curl 
          - dkms 
          - build-essential 
          - cmake 
          - cmake-data 
          - openssh-server 
          - alsa-utils
    - name: Add i3 ppa
      apt_repository: 
        repo: deb http://ppa.launchpad.net/regolith-linux/release/ubuntu focal main
        filename: regolith
    - name: Add spotify ppa
      apt_repository:
        repo: deb http://repository.spotify.com stable non-free
        filename: spotify
    - name: Install dev utils
      apt:
        name:
          - stow 
          - zsh 
          - zsh-antigen 
          - ranger 
          - silversearcher-ag 
          - openvpn
          - jq
          - graphviz
          - htop
          - exa
          - neovim
          - neovim-runtime
          - i3-gaps
          - diff-so-fancy
          - tsserver
          - bat
          - hub
          - fzf
        update_cache: yes
    - name: Install secondary deps
      apt:
        name: 
          - libcairo2-dev 
          - libxcb1-dev 
          - libxcb-ewmh-dev 
          - libxcb-icccm4-dev 
          - libxcb-image0-dev 
          - libxcb-randr0-dev 
          - libxcb-util0-dev 
          - libxcb-xkb-dev 
          - pkg-config 
          - python-xcbgen 
          - xcb-proto 
          - libxcb-xrm-dev 
          - libasound2-dev 
          - libmpdclient-dev 
          - libiw-dev 
          - libcurl4-openssl-dev 
          - libpulse-dev 
          - libxcb-keysyms1-dev 
          - libpango1.0-dev 
          - libxcb-util0-dev 
          - xcb 
          - libxcb1-dev 
          - libxcb-icccm4-dev 
          - libyajl-dev 
          - libev-dev 
          - libxcb-xkb-dev 
          - libxcb-cursor-dev 
          - libxkbcommon-dev 
          - libxcb-xinerama0-dev 
          - libxkbcommon-x11-dev 
          - libstartup-notification0-dev 
          - libxcb-randr0-dev 
          - libxcb-xrm0 
          - libxcb-xrm-dev 
          - libxcb-composite0-dev 
          - sudo
          - chromium 
          - xfonts-base 
          - xserver-xorg-input-all 
          - xinit 
          - xserver-xorg 
          - xserver-xorg-video-all 
          - cargo 
          - tig 
          - feh 
          - tmux 
          - compton 
          - suckless-tools 
          - xclip 
          - nodejs 
          - bison 
          - flex
          - dbus-x11 
          - libdbus-1-dev 
          - libx11-dev 
          - libxinerama-dev 
          - libxrandr-dev 
          - libxss-dev 
          - libglib2.0-dev 
          - libpango1.0-dev 
          - libgtk-3-dev 
          - libxdg-basedir-dev 
          - dirmngr 
          - ffmpeg 
          - x11-apps 
          - librsvg-2 
          - mpc
          - spotify
    - name: Add ssh key
      shell: >
        ssh-keygen -t rsa -b 4096 -C "maxi.bertrand@gmail.com"
    - name: Install chrome
      shell: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -O chrome.deb
        dpkg -i chrome.deb
      args:
        chdir: /tmp
    - name: Clone dunst
      git:
        repo: https://github.com/dunst-project/dunst.git
        dest: /tmp/dunst
    - name: Install dunst
      shell: |
        make
        make install
      args:
        chdir: /tmp/dunst
    - name: Clone rofi
      git:
        repo: https://github.com/DaveDavenport/rofi
        dest: /tmp/rofi
    - name: Install rofi
      shell: |
        mdkir build && cd build
        ../configure
        make
        make install
      args:
        chdir: /tmp/dunst
    - name: Install rust & cargo
      shell: | 
        curl https://sh.rustup.rs -sSf | sh
        source $HOME/.cargo/env
        rustup override set stable
        rustup update stable
    - name: Clone alacritty repo
      git: 
        repo: https://github.com/jwilm/alacritty.git
        dest: /tmp/alacritty
        version: v0.2.1
    - name: Build alacritty
      shell: >
        cargo build --release
    - name: Install alacritty
      copy:
        src: /tmp/alacritty/releases/target/alacritty
        dest: /usr/bin/alacritty
        mode: a+x
    - name: Clone polybar
      git:
        repo: https://github.com/jaagr/polybar.git
        dest: /tmp/polybar
    - name: Install polybar
      script: build.sh
      args:
        chdir: /tmp/polybar
    - name: Recdsk
      copy:
        src: recdsk
        dest: /usr/bin/recdsk
        mode: a+x
    - name: Install fonts
      copy:
        src: "{{ item }}"
        dest: /usr/share/fonts
      with_fileglob:
        - fonts/*
    - name: Update fonts cache
      shell: fc-cache -fv
    - name: Install VPN
      file:
        src: init.d/openvpncustom
        dest: /etc/init.d/openvpncustom
        state: link
    # - name: Install i3lock-color
    - name: Install nvm
      shell: >
        wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
    - name: Install node
      ansible.builtin.shell: |
        nvm install {{ item }}
        nvm use {{ item }}
      loop:
        - 16.13.0
    - name: Wrap up
      script: install.sh
      become_user: monzey

