---
- hosts: localhost
  become: yes
  tasks:
    - name: Swap keyboard layout
      replace:
        path: /etc/default/keyboard
        regexp: 'us'
        replace: 'fr'
    - name: Install core
      apt:
        name:
          - dkms 
          - build-essential 
          - cmake 
          - cmake-data 
          - openssh-server 
          - alsa-utils
          - autconf
    - name: Add regolith key
      apt_key:
        url: https://regolith-linux.github.io/package-repo/regolith.key
        state: present
    - name: Add regolith ppa
      apt_repository: 
        repo: deb https://regolith-linux.github.io/package-repo/unstable/debian/bullseye/amd64 bullseye main
        filename: regolith
    - name: Add spotify key
      apt_key:
        url: https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg
        state: present 
    - name: Add spotify ppa
      apt_repository:
        repo: deb http://repository.spotify.com stable non-free
        filename: spotify
    - name: Add diff-so-fancy key
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: 4466B73F97EF279EC64D8A169E8A0C808486162E
    - name: Add diff-so-fancy ppa
      apt_repository:
        repo: deb http://ppa.launchpad.net/aos1/diff-so-fancy/ubuntu focal main
        filename: diffsofancy
    - name: Install dev utils
      apt:
        name:
          - stow 
          - zsh 
          - ranger 
          - silversearcher-ag 
          - openvpn
          - jq
          - graphviz
          - htop
          - exa
          - neovim
          - neovim-runtime
          - i3-gaps
          - diff-so-fancy
          - bat
          - hub
          - fzf
          - rofi
          - unzip
          - zip
        update_cache: yes
    - name: Install secondary deps
      apt:
        name: 
          - libcairo2-dev 
          - libxcb1-dev 
          - libxcb-ewmh-dev 
          - libxcb-icccm4-dev 
          - libxcb-image0-dev 
          - libxcb-randr0-dev 
          - libxcb-util0-dev 
          - libxcb-xkb-dev 
          - pkg-config 
          - python3-xcbgen 
          - xcb-proto 
          - libxcb-xrm-dev 
          - libasound2-dev 
          - libmpdclient-dev 
          - libiw-dev 
          - libcurl4-openssl-dev 
          - libpulse-dev 
          - libxcb-keysyms1-dev 
          - libpango1.0-dev 
          - libxcb-util0-dev 
          - xcb 
          - pkg-config 
          - libpam0g-dev 
          - libcairo2-dev 
          - libfontconfig1-dev 
          - libxcb-composite0-dev 
          - libev-dev 
          - libx11-xcb-dev 
          - libxcb-xkb-dev 
          - libxcb-xinerama0-dev 
          - libxcb-randr0-dev 
          - libxcb-image0-dev 
          - libxcb-util0-dev 
          - libxcb-xrm-dev 
          - libxcb-xtest0-dev 
          - libxkbcommon-dev 
          - libxkbcommon-x11-dev 
          - libjpeg-dev
          - libxcb-xrm-dev
          - libxcb1-dev 
          - libxcb-icccm4-dev 
          - libyajl-dev 
          - libev-dev 
          - libxcb-xkb-dev 
          - libxcb-cursor-dev 
          - libxkbcommon-dev 
          - libxcb-xinerama0-dev 
          - libxkbcommon-x11-dev 
          - libstartup-notification0-dev 
          - libxcb-randr0-dev 
          - libxcb-xrm0 
          - libxcb-xrm-dev 
          - libxcb-composite0-dev 
          - sudo
          - chromium 
          - xfonts-base 
          - xserver-xorg-input-all 
          - xinit 
          - xserver-xorg 
          - xserver-xorg-video-all 
          - cargo 
          - tig 
          - feh 
          - tmux 
          - compton 
          - suckless-tools 
          - xclip 
          - bison 
          - flex
          - dbus-x11 
          - libdbus-1-dev 
          - libx11-dev 
          - libxinerama-dev 
          - libxrandr-dev 
          - libxss-dev 
          - libglib2.0-dev 
          - libpango1.0-dev 
          - libgtk-3-dev 
          - libxdg-basedir-dev 
          - dirmngr 
          - ffmpeg 
          - x11-apps 
          - librsvg2-2 
          - mpc
          - spotify-client
          - libdbus-1-dev 
          - libx11-dev 
          - libxinerama-dev 
          - libxrandr-dev 
          - libxss-dev 
          - libglib2.0-dev 
          - libpango1.0-dev 
          - libgtk-3-dev 
          - libxdg-basedir-dev 
          - libnotify-dev
          - polybar
        update_cache: yes
    - name: Install antigen
      get_url:
        url: git.io/antigen
        dest: /urs/local/bin/antigen
    - name: Add ssh directory
      file:
        path: ~/.ssh
        state: directory
        mode: '0755'
      become_user: monzey
    - name: Add ssh key
      community.crypto.openssh_keypair:
        path: ~/.ssh/id_rsa
        size: 4096
        type: rsa
        comment: maxi.bertrand@gmail.com
      become_user: monzey
    - name: Install chrome
      shell: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -O chrome.deb
        dpkg -i chrome.deb
      args:
        chdir: /tmp
    - name: Clone dunst
      git:
        repo: https://github.com/dunst-project/dunst.git
        dest: /tmp/dunst
    - name: Install dunst
      shell: |
        make
        make install
      args:
        chdir: /tmp/dunst
    - name: Remove current rustc
      apt:
        name: rustc
        state: absent
    - name: Install rust
      shell: | 
        curl https://sh.rustup.rs -sSf | sh -s -- -y
    - name: Clone i3lock-color
      git:
        repo: https://github.com/Raymo111/i3lock-color.git
        dest: /tmp/i3lock-color
    - name: Install i3lock-color
      shell: |
        ./install-i3lock-color.sh
      args:
        chdir: /tmp/i3lock-color
    - name: Install alacritty
      block:
        - name: Install alacritty globaly
          shell: cargo install alacritty
        - name: Install alacritty for user
          copy: 
            src: /$HOME/.cargo/bin/alacritty
            dest: /usr/bin/alacritty
            mode: '0755'
    - name: Install vscode
      apt:
        deb: https://az764295.vo.msecnd.net/stable/899d46d82c4c95423fb7e10e68eba52050e30ba3/code_1.63.2-1639562499_amd64.deb
    - name: Install libappindicator
      apt:
        deb: http://ftp.fr.debian.org/debian/pool/main/liba/libappindicator/libappindicator3-1_0.4.92-7_amd64.deb
    - name: Install libindicator
      apt:
        deb: http://ftp.fr.debian.org/debian/pool/main/libi/libindicator/libindicator3-7_0.5.0-4_amd64.deb
    - name: Install slack
      apt:
        deb: https://downloads.slack-edge.com/releases/linux/4.23.0/prod/x64/slack-desktop-4.23.0-amd64.deb
    - name: Install virtualbox
      block:
        - name: Add vbox repo
          apt_repository: 
            repo: deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian bullseye contrib
        - name: Add vbox 2016 key
          apt_key:
            url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
            state: present
        - name: Add vbox key
          apt_key:
            url: https://www.virtualbox.org/download/oracle_vbox.asc
            state: present
        - name: Install vbox
          apt:
            name: virtualbox-6.1
            update_cache: yes
        - name: Download extension pack
          get_url:
            url: https://download.virtualbox.org/virtualbox/6.1.30/Oracle_VM_VirtualBox_Extension_Pack-6.1.30.vbox-extpack
            dest: /tmp/extpack-6.1.30.vbox-extpack
        - name: Install extension pack
          shell: vboxmanage extpack install /tmp/extpack-6.1.30.vbox-extpack
    - name: Install vagrant
      block:
        - name: Add vagrant repo
          apt_repository:
            repo: deb [arch=amd64] https://apt.releases.hashicorp.com bullseye main
        - name: Add vagrant repo key
          apt_key:
            url: https://apt.releases.hashicorp.com/gpg
        - name: Install vagrant package
          apt:
            name: vagrant
            update_cache: yes
    - name: Recdsk
      copy:
        src: recdsk
        dest: /usr/bin/recdsk
        mode: a+x
    - name: Install fonts
      copy:
        src: "{{ item }}"
        dest: /usr/share/fonts
      with_fileglob:
        - fonts/*
    - name: Update fonts cache
      shell: fc-cache -fv
    - name: Install VPN
      file:
        src: "{{ playbook_dir }}/init.d/openvpncustom"
        dest: /etc/init.d/openvpncustom
        state: link
    - name: Install nvm
      shell: |
        wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
      become_user: monzey
    - name: Install node 
      shell: |
        source $HOME/.nvm/nvm.sh
        nvm install {{ item }}
        nvm use {{ item }}
      args:
        executable: /bin/bash
      loop:
        - 16.13.0
      become_user: monzey
    - name: Clone dotfiles
      git:
        repo: https://github.com/monzey/dotfiles.git
        dest: $HOME/dotfiles
      become_user: monzey
    - name: Change chsh permissions
      replace:
        path: /etc/pam.d/chsh
        regexp: 'required'
        replace: 'sufficient'
    - name: Wrap up user install
      script: install.sh
      args:
        chdir: /home/monzey/dotfiles
      become_user: monzey
    - name: Install devbox
