#! /bin/bash 

cd ~/dotfiles
pwd=`pwd`

stow alacritty
stow autostart
stow bat
stow compton
stow dunst
stow feh
stow git
stow i3
stow ncmpcpp
stow polybar
stow qutebrowser
stow ranger
stow rofi
stow tern
stow tig
stow tmux
stow vim
stow x
stow zsh

chsh -s $(which zsh)

folder=`~/.tmux/plugins/tpm`

if [ ! -d "$folder" ] ; then
  git clone https://github.com/tmux-plugins/tpm "$folder"
fi

mkdir -p ~/.icons/cursor-default-theme
cp -r cursor/* ~/.icons/cursor-default-theme

ln -sf $pwd/.fonts.conf ~

cd ~
