fork = false
frame = "full"
idle = true
maximized = false
mouse-cursor-icon = "arrow"
no-multigrid = false
srgb = false
tabs = true
theme = "auto"
title-hidden = true
vsync = true
wsl = false

[font]
normal = "VictorMono Nerd Font" 
size = 16
bold = "VictorMono Nerd Font"

[box-drawing]
# "font-glyph", "native" or "selected-native"
mode = "font-glyph"

[box-drawing.sizes]
default = [4, 6]
